name: Docker Hub Pipeline

on:
  push:
    branches:
      - main  # Ana branch'e her push olduğunda bu workflow çalışacak
  workflow_dispatch:  # Manuel olarak çalıştırmak için tetikleme

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Docker Hub'a giriş yap
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Docker imajını pull et
    - name: Pull Docker Image
      run: |
        docker pull ayseknd/alistirma:testinium.v2

    # Docker imajını çalıştır
    - name: Run Docker Image
      run: |
        docker run -d --name my-container ayseknd/alistirma:testinium.v2

    
    # Docker imajını build et ve push et (yeni bir versiyon varsa)
    - name: Build and Push Docker Image
      run: |
        docker build -t ayseknd/alistirma:testinium.v2 .
        docker push ayseknd/alistirma:testinium.v2
