name: Docker Hub Image Update and Test

on:
  push:
    branches:
      - main  # main branch'ine yapılan push'lar tetikleyecek
  workflow_dispatch:  # Manuel tetikleme için (opsiyonel)

jobs:
  # İlk job: Docker imajını çekip çalıştır
  pull_and_run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Docker Hub'a giriş yap
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Docker Hub'dan imajı çek
    - name: Pull Docker Image from Docker Hub
      run: |
        docker pull ayseknd/alistirma:testinium.v2

    # Docker imajını çalıştır
    - name: Run Docker Container
      run: |
        docker run -d --name test-container -p 8080:8080 ayseknd/alistirma:testinium.v2

  # İkinci job: Konteynerin başlatıldığını doğrulamak için hazır olup olmadığını kontrol et
  test_container_ready:
    runs-on: ubuntu-latest
    needs: pull_and_run  # pull_and_run job'ının tamamlanmasını bekler

    steps:
    - name: Wait for container to be ready
      run: |
        # Konteynerin başlatıldığını kontrol et
        timeout=0
        while ! docker ps -q -f name=test-container; do
          if [ $timeout -ge 60 ]; then
            echo "Konteyner başlatılamadı! Zaman aşımı."
            exit 1
          fi
          echo "Konteyner henüz başlatılmadı, tekrar deneniyor..."
          docker ps -a 
          sleep 5  
          timeout=$((timeout + 5))
        done
        echo "Konteyner başarıyla başlatıldı!"

  # Üçüncü job: Konteynerin çalışıp çalışmadığını test et
  test_container:
    runs-on: ubuntu-latest
    needs: test_container_ready  # test_container_ready job'ının tamamlanmasını bekler

    steps:
    - name: Test Docker Container
      run: |
        docker ps -a  
        docker exec test-container curl http://localhost:8080  

  # Dördüncü job: Docker konteynerini durdur ve sil
  clean_up:
    runs-on: ubuntu-latest
    needs: test_container  # test_container job'ının tamamlanmasını bekler

    steps:
    - name: Clean up Docker Container
      run: |
        docker stop test-container
        docker rm test-container
