name: Docker Hub Image Update and Test

on:
  push:
    branches:
      - main  # main branch'ine yapılan push'lar tetikleyecek
  workflow_dispatch:  # Manuel tetikleme için (opsiyonel)

jobs:
  # İlk job: Docker imajını çekip çalıştır
  pull_and_run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Docker Hub'a giriş yap
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Docker Hub'dan imajı çek
    - name: Pull Docker Image from Docker Hub
      run: |
        docker pull ayseknd/alistirma:testinium.v2

    # Docker imajını çalıştır
    - name: Run Docker Container
      run: |
        docker run -d --name test-container -p 8080:8080 ayseknd/alistirma:testinium.v2

  # İkinci job: Konteynerin çalışıp çalışmadığını test et
  wait_for_container:
    runs-on: ubuntu-latest
    needs: pull_and_run  # pull_and_run job'ının tamamlanmasını bekler

    steps:
    - name: Wait for container to be ready
      run: |
        docker ps -q -f "name=test-container"  # Konteynerin çalıştığından emin ol

  # Üçüncü job: Konteyneri test et
  test_container:
    runs-on: ubuntu-latest
    needs: wait_for_container  # wait_for_container job'ının tamamlanmasını bekler

    steps:
    - name: Test Docker Container
      run: |
        docker exec test-container curl http://localhost:8080  # Burada doğru portu kullandığınızdan emin olun

  # Dördüncü job: Docker konteynerini durdur ve sil
  clean_up:
    runs-on: ubuntu-latest
    needs: test_container  # test_container job'ının tamamlanmasını bekler

    steps:
    - name: Clean up Docker Container
      run: |
        docker stop test-container
        docker rm test-container
